### ISSUE TITLE
extension.json license

### ISSUE THREAD

**Issue by chaud** [NilsEnevoldsen/AudioButton#2]
https://github.com/NilsEnevoldsen/AudioButton/blob/02fab02427dd9808bcf63fcc6635dcd5c83e7512/extension.json#L9

Should this be a difference license? The included file is not MIT: https://github.com/NilsEnevoldsen/AudioButton/blob/master/COPYING

**Comment by NilsEnevoldsen** [comment]
I intended the license to be MIT. I will replace the GPL license file with the MIT license file. Let me know if this presents any issues.
