### ISSUE TITLE
File uses should create a link to the file

### ISSUE THREAD

**Issue by pcjcos** [NilsEnevoldsen/AudioButton#9]
On Dota2 we had a bunch of files that were moved without updating the page incorporating them because there were no links generated by their use through this extension. It would be helpful if using a file in this extension added a link from the calling page to the file.

**Comment by NilsEnevoldsen** [comment]
Somebody asked that [here](https://www.mediawiki.org/wiki/Topic:U8f6wrc5ryzty0ac). I agree, but I don't know how to accomplish this. One user said it would involve writing to the imagelinks table. I should take another look.

**Comment by NilsEnevoldsen** [comment]
Thanks!
